apiVersion: v1
kind: Pod
metadata:
  name: taxidata
  namespace: emr-data-team-a
spec:
  nodeSelector:
    eks.amazonaws.com/capacityType: ON_DEMAND
    topology.kubernetes.io/zone: eu-west-1b
#    node.kubernetes.io/instance-type: m5.xlarge
